### ISSUE TITLE
admob_flutter/AdmobFlutterPlugin.h file not found |GeneratedPluginRegistrant.m

### ISSUE THREAD

**Issue by hyperpanthera** [YoussefKababe/admob_flutter#44]

**Comment by tanliubin** [comment]
> _No description provided._

Is it solved? I also have this problem.

**Comment by hyperpanthera** [comment]
@tanliubin I fixed it by recreating a Flutter project with Swift support.

**Comment by kmcgill88** [comment]
We should probably document this is using Swift. Would either of you be willing to make a PR to the Readme? 😃

**Comment by praharshbhatt** [comment]
@hyperpanthera I tried this by deleting the ios folder and doing "flutter create -i ios ."
unfortunately, the Same issue persists :(

**Comment by hyperpanthera** [comment]
@praharshbhatt You gotta do -i swift and not -i ios.

**Comment by praharshbhatt** [comment]
Sorry, I did the same. Now I am getting 
"ambiguous reference to member swift error .setcategory()" 
Error.
What do i do now?

**Comment by hyperpanthera** [comment]
@praharshbhatt Recreate a Flutter project from scratch.

**Comment by lockelost** [comment]
New project creation does not help in my case.

Is that header created under "<project path>/ios/Pods/Target\ Support\ Files/admob_flutter" ?
Can you just share the header file here?

**Comment by lockelost** [comment]
Found the solution
https://github.com/flutter/flutter/issues/16246#issuecomment-454306108
